Update user_account for Chef13
tamucookbooks/user_account pull request #5
Opened 2017-02-01 21:02 UTC by rearview

2017-02-01 21:53 UTC, jarosser06 requested changes

2017-02-01 21:53 UTC, jarosser06 commented on metadata.rb
> +version          '1.1.1'
Can you remove this version bump. Version bumps should be in master.

2017-02-01 21:56 UTC, rearview commented
Will do.


Chris Rutledge | Systems Administrator 2
Digital Initiatives | Texas A&M University Libraries
Tel. 979.458.5588 | Fax 979.845.6238

From: Jim Rosser <notifications@github.com>
Reply-To: tamucookbooks/user_account <reply@reply.github.com>
Date: Wednesday, February 1, 2017 at 3:53 PM
To: tamucookbooks/user_account <user_account@noreply.github.com>
Cc: Chris Rutledge <crutledge@library.tamu.edu>, Author <author@noreply.github.com>
Subject: Re: [tamucookbooks/user_account] Update user_account for Chef13 (#5)


@jarosser06 requested changes on this pull request.

________________________________

In metadata.rb<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tamucookbooks_user-5Faccount_pull_5-23pullrequestreview-2D19665790&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=2F9wxw0WtoVIHbvIoZRlKV1yIlc1FWrPSvR-NkLoGxw&s=ogqSv4dB3RqQpknrEkJbcURbBNFFU1l-JsfggDEHbyY&e=>:

> @@ -4,7 +4,7 @@

 license          'MIT'

 description      'Provides a resource for user_account'

 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))

-version          '1.1.0'

+version          '1.1.1'

Can you remove this version bump. Version bumps should be in master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tamucookbooks_user-5Faccount_pull_5-23pullrequestreview-2D19665790&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=2F9wxw0WtoVIHbvIoZRlKV1yIlc1FWrPSvR-NkLoGxw&s=ogqSv4dB3RqQpknrEkJbcURbBNFFU1l-JsfggDEHbyY&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHf0Sz-5Fteua32HoqI2oQsYAJO6XeeuG2ks5rYP7CgaJpZM4L0YdE&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=2F9wxw0WtoVIHbvIoZRlKV1yIlc1FWrPSvR-NkLoGxw&s=OxPw1uN44C4ZiWKpNHFzCgnoZm_dinH5U4lawyjQ8Es&e=>.

2017-02-01 21:56 UTC, rearview reviewed
bumped version back down.

2017-02-01 21:56 UTC, rearview commented
version bumped back down.

2017-02-01 21:56 UTC, jarosser06 commented
Looks good, can you squash these commits to a single commit.

2017-02-01 22:39 UTC, rearview commented
I’m tryig to figure out how.  This is a first for me.


Chris Rutledge | Systems Administrator 2
Digital Initiatives | Texas A&M University Libraries
Tel. 979.458.5588 | Fax 979.845.6238

From: Jim Rosser <notifications@github.com>
Reply-To: tamucookbooks/user_account <reply@reply.github.com>
Date: Wednesday, February 1, 2017 at 3:56 PM
To: tamucookbooks/user_account <user_account@noreply.github.com>
Cc: Chris Rutledge <crutledge@library.tamu.edu>, Author <author@noreply.github.com>
Subject: Re: [tamucookbooks/user_account] Update user_account for Chef13 (#5)


Looks good, can you squash these commits to a single commit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tamucookbooks_user-5Faccount_pull_5-23issuecomment-2D276795775&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=WfSStwHWTeYQ0hpYfxQQPS9albOpOfWaB81Ipq8Lzag&s=J_CK3HL25adJ81-CiDq6A55T-GQTvFIDN8rRTJ1UXNI&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHf0S0RXu2COcSy-5Foa04RNce8M3mrQRFks5rYP-2DggaJpZM4L0YdE&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=WfSStwHWTeYQ0hpYfxQQPS9albOpOfWaB81Ipq8Lzag&s=97tRwFWluMeaz1FMd9I2og_CVIpIqrd1qA2893JGh18&e=>.

2017-02-02 14:59 UTC, rearview commented
Okay check that.


Chris Rutledge | Systems Administrator 2
Digital Initiatives | Texas A&M University Libraries
Tel. 979.458.5588 | Fax 979.845.6238

From: Jim Rosser <notifications@github.com>
Reply-To: tamucookbooks/user_account <reply@reply.github.com>
Date: Wednesday, February 1, 2017 at 3:56 PM
To: tamucookbooks/user_account <user_account@noreply.github.com>
Cc: Chris Rutledge <crutledge@library.tamu.edu>, Author <author@noreply.github.com>
Subject: Re: [tamucookbooks/user_account] Update user_account for Chef13 (#5)


Looks good, can you squash these commits to a single commit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tamucookbooks_user-5Faccount_pull_5-23issuecomment-2D276795775&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=WfSStwHWTeYQ0hpYfxQQPS9albOpOfWaB81Ipq8Lzag&s=J_CK3HL25adJ81-CiDq6A55T-GQTvFIDN8rRTJ1UXNI&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHf0S0RXu2COcSy-5Foa04RNce8M3mrQRFks5rYP-2DggaJpZM4L0YdE&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=WfSStwHWTeYQ0hpYfxQQPS9albOpOfWaB81Ipq8Lzag&s=97tRwFWluMeaz1FMd9I2og_CVIpIqrd1qA2893JGh18&e=>.

2017-02-02 15:07 UTC, jarosser06 commented
That added more commits. Try ```git rebase -i HEAD~6```

2017-02-02 20:24 UTC, rearview commented
There you go.


Chris Rutledge | Systems Administrator 2
Digital Initiatives | Texas A&M University Libraries
Tel. 979.458.5588 | Fax 979.845.6238

From: Jim Rosser <notifications@github.com>
Reply-To: tamucookbooks/user_account <reply@reply.github.com>
Date: Thursday, February 2, 2017 at 9:07 AM
To: tamucookbooks/user_account <user_account@noreply.github.com>
Cc: Chris Rutledge <crutledge@library.tamu.edu>, Author <author@noreply.github.com>
Subject: Re: [tamucookbooks/user_account] Update user_account for Chef13 (#5)


That added more commits. Try git rebase -i HEAD~6

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tamucookbooks_user-5Faccount_pull_5-23issuecomment-2D276982540&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=-SXGYa2QEUdxitnjPvR-ElS4HmRPfclPd08K4C_N_Cc&s=HDfDlC7RDeA_SX4TMCMMU0kpBYS2Y7aM3cVc6SWIxVU&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHf0S0SkhCpemazmaUaQJY5N4QSdjj-5F-2Dks5rYfEkgaJpZM4L0YdE&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=djn2f9OOI963UYKQwW1Lc_vc-RWjDkWhPIDjm60GKLE&m=-SXGYa2QEUdxitnjPvR-ElS4HmRPfclPd08K4C_N_Cc&s=oEybJEnO1SLI8ZiO7Qc8HuTN_Hl7-peWxqdqsX7nk2E&e=>.

2017-02-09 18:30 UTC, jarosser06 commented
I updated the commit and merged it into master.

2017-02-09 18:30 UTC, closed without merging